config/routes.rb
Iboard::Application.routes.draw do
  root to: 'tops#index'

  resources :tops, only: :index
  resources :topics, only: [:show, :new, :create, :destroy] do
    resources :comments, only: [:new, :create, :destroy]
  end

  match "/auth/:provider/callback" => "sessions#callback"
  match "/auth/failure" => "sessions#failure"
  match "/logout" => "sessions#destroy", as: :logout
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Ownerships

  attr_accessible :body, :user_id

  belongs_to :user
  belongs_to :topic

  validates :body, presence: true, length: { maximum: 300 }
end

app/models/concerns/ownerships.rb
module Ownerships
  def owned_by?(user)
    self.user == user
  end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  include Ownerships

  attr_accessible :title, :user_id

  belongs_to :user
  has_many :comments

  validates :title, presence: true, length: { maximum: 100 }
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :display_name, :name, :provider, :uid

  has_many :topics
  has_many :comments

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider     = auth["provider"]
      user.uid          = auth["uid"]
      user.name         = auth["info"]["name"]
      user.display_name = auth["info"]["nickname"]
    end 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def login_required
    redirect_to root_path, notice: 'you are not logged in.' unless current_user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :login_required, :find_topic

  def new
    @comment = @topic.comments.new
  end

  def create
    @comment = @topic.comments.new(params[:comment])
    @comment.user = current_user
    if @comment.save
      redirect_to topic_path(@topic), notice: 'Comment was successfully created.'
    else
      render action: :new
    end
  end

  def destroy
    @comment = @topic.comments.find(params[:id])
    if @comment.owned_by?(current_user)
      @comment.destroy
      redirect_to topic_path(@topic), notice: 'Comment was successfully deleted.'
    else
      redirect_to topic_path(@topic), notice: 'Forbidden'
    end
  end

  private
  def find_topic
    @topic = Topic.find(params[:topic_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def callback
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"])

    if user
      session[:user_id] = user.id
      redirect_to root_path, notice: 'logged in successfully.'
    else
      created_user = User.create_with_omniauth(auth)
      session[:user_id] = created_user.id
      redirect_to root_path, notice: 'authenticated and logged in successfully.'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'logged out.'
  end

  def failure
    render text: 'twitter auth failed.'
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_filter :login_required, except: :show 
  before_filter :find_topic, only: [:show, :destroy]
  before_filter :owner_required, only: :destroy

  def show
  end

  def new
    @topic = current_user.topics.new
  end

  def create
    @topic = current_user.topics.new(params[:topic])
    if @topic.save
      redirect_to root_path, notice: 'Topic was successfully created.'
    else
      render action: :new
    end
  end

  def destroy
    @topic.destroy
    redirect_to root_path, notice: "#{@topic.title} was successfully deleted."
  end

  private
  def find_topic
    @topic = Topic.find(params[:id])
  end

  def owner_required
    redirect_to root_path, notice: 'Forbidden' unless @topic.owned_by?(current_user)
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
    @topics = Topic.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/comments/_form.html.haml
= form_for @comment, url: topic_comments_path(@comment.topic) do |f|
  -if @comment.errors.any?
    #error_explanation
      %h2= "#{pluralize(@comment.errors.count, "error")} prohibited this comment from being saved:"
      %ul
        - @comment.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :body
    = f.text_area :body
  .actions
    = f.submit 'Save'

app/views/comments/_list.html.haml
- if @topic.comments.empty?
  %p No Comment
- else
  %h2 Comment List
  - @topic.comments.each do |comment|
    %div.comment{id: comment.id, style: 'border-bottom: 1px solid #ccc;'}
      = simple_format comment.body
      %br
      = "(created by #{comment.user.try(:display_name) || 'unknown'})"
      - if current_user && comment.owned_by?(current_user)
        = link_to 'Destroy', topic_comment_path(@topic, comment), id: 'destroy-comment', data: { confirm: 'Are you sure?' }, method: :delete

app/views/comments/new.html.haml
%h1= "New comment for #{@topic.title}"
 
= render 'form'

= link_to 'Back to Top', root_path
\/
= link_to 'Back', topic_path(@topic)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title iboard
    = stylesheet_link_tag :application, media: "all"
    = javascript_include_tag :application
    = csrf_meta_tags

  %body
    = yield 

app/views/topics/_form.html.haml
= form_for @topic do |f|
  -if @topic.errors.any?
    #error_explanation
      %h2= "#{pluralize(@topic.errors.count, "error")} prohibited this topic from being saved:"
      %ul
        - @topic.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .actions
    = f.submit 'Save'

app/views/topics/new.html.haml
%h1 New topic

= render 'form'

= link_to 'Back', root_path

app/views/topics/show.html.haml
%p
  %b Title:
  = @topic.title
%p
  %b User:
  = @topic.user.try(:display_name)

- if current_user && @topic.owned_by?(current_user)
  %p= link_to 'Destroy', topic_path(@topic), id: 'destroy-topic', data: { confirm: 'Are you sure?' }, method: :delete
  
%hr

- if flash[:notice]
  %p#notice= flash[:notice]

- if current_user
  = link_to 'New Comment', new_topic_comment_path(@topic)

= render partial: 'comments/list'

%p= link_to 'Back', root_path

app/views/tops/index.html.haml
%h1 iboard

- if current_user.nil?
  %p= link_to 'Twitter Login', '/auth/twitter'
- else
  %p= current_user.display_name
  %p= link_to 'Logout', logout_path

%hr

- if flash[:notice]
  %p#notice= flash[:notice]

- if current_user
  = link_to 'New Topic', new_topic_path

- if @topics.empty?
  %p No Topics
- else
  %h2 Topic List
  %ul
    - @topics.each do |topic|
      %li= link_to topic.title, topic_path(topic)
      = "created_by #{topic.user.try(:display_name)}"